---
title: "Ch3-MPAcosts"
---

# Loading packages needed fro the project
```{r}
library(readr)
library(ggplot2)
library(maps)
```

# Making a map of the MPAs I found data for 
## Loading the data
```{r}
#upload the right data
#pres <- read_csv("../pres.csv")
```

## Making global map with my data
```{r}
# Get world map data
world_map <- map_data("world")

png("Map1.png", width = 2100, height = 1800, res = 150)
# Create the world map
ggplot(data = world_map) + 
  geom_polygon(aes(x = long, y = lat, group = group), color = "black", fill = NA) +  
  coord_fixed(ratio = 1.1) +  
  theme_minimal() + 
  theme(axis.text = element_text(size = 24),  # Increased size for axis labels (tick labels)
        axis.title = element_text(size = 24),  # Increased size for axis titles
        axis.line.x = element_line(color = "black", size = 0.5),  # X-axis line
        axis.line.y = element_line(color = "black", size = 0.5),  # Y-axis line
        axis.ticks = element_line(color = "black", size = 0.5),  # Add ticks to both axes
        panel.grid = element_blank()) +  # Optional: remove grid lines
  geom_point(data = pres, aes(x = Longitude, y = Latitude), color = "#008080", size = 6) +  
  labs(x = "Longitude", y = "Latitude")
  

dev.off()

```


