---
title: "Figures"
format: html
---

# Library

```{r}
library(ggplot2)
library(dplyr)
library(patchwork)
```

# Figure 3: Costs of establishment phase for each degree of protection

```{r}
# making prediction 
esubs <- esubs |> 
  filter(!is.na(Years)) 

pred_draws1 <- emmeans(
  esubs.brm1,
  ~ Years | Protection_level,
  at = list(
    Years = seq(min(esubs$Years), max(esubs$Years), length.out = 100),
    lSize = mean(esubs$lSize, na.rm = TRUE),
    Protection_level = unique(esubs$Protection_level))) |>
  gather_emmeans_draws()

pred_year1 <- pred_draws1 |>
  group_by(Years, Protection_level) |>
  summarise(
    estimate = median(.value),
    lower = quantile(.value, 0.025),
    upper = quantile(.value, 0.975),
    .groups = "drop"
  ) |>
  mutate(
    median = exp(estimate),
    lower = exp(lower),
    upper = exp(upper))

# plotting 
fpey <- subset(pred_year1, Protection_level == "Fully protected")
mubsey <- subset(pred_year1, Protection_level == "Partially protected")
# Create the plot - base plot 
neyear_pl <- 
  ggplot() +
  # Fully protected areas
  geom_line(data = fpey, aes(x = Years, y = median, color = "Fully protected areas"), size = 0.8) + #, linetype = "dashed") +
  geom_ribbon(data = fpey, aes(x = Years, ymin = lower, ymax = upper, fill = "Fully protected areas"), alpha = 0.2) +
  # Partially protected areas
  geom_line(data = mubsey, aes(x = Years, y = median, color = "Multi-use areas"), size = 0.8) + #, linetype = "dashed") +
  geom_ribbon(data = mubsey, aes(x = Years, ymin = lower, ymax = upper, fill = "Multi-use areas"), alpha = 0.2) +
  # Customize scales
  scale_color_manual(values = c("Fully protected areas" = "#0072B2", "Multi-use areas" = "#E69F00")) +
  scale_fill_manual(values = c("Fully protected areas" = "#0072B2", "Multi-use areas" = "#E69F00")) +
  # Scientific notation for y-axis
  #scale_y_continuous(
    #labels = scales::label_number(), 
                     #limits=c(0, 1e06)) +
scale_y_continuous(
  labels = scales::label_number()
  # remove limits= here
) +
coord_cartesian(ylim = c(0, 1e6), clip = "on") +  # zoom without dropping rows
  # Apply theme
  theme_bw() +
  theme(text = element_text(family = "serif"), 
        #panel.grid.major = element_blank(),
        #panel.grid.minor = element_blank(), 
        legend.position = "right", 
        #axis.title = element_blank(), # remove axis titles
        panel.border = element_rect(colour = "black", fill = NA, size = 0.25) # change thickness of the outside boarder
        ) +
  guides(
    color = guide_legend(
      override.aes = list(linetype = "solid")  # show solid lines in legend
    )) +
  # Labels
  labs(
    x = "Establishment phase (years)",
    y = "Estimated establishment costs (US$/km²)",
    color = "Degree of Protection",
    fill = "Degree of Protection")

# Creating inset plot with log10 scale for the y axis
leyear_pl <- 
  ggplot() +
  geom_line(data = fpey, aes(x = Years, y = median), color = "#0072B2", size = 0.8) + #, linetype = "dashed") +
  geom_line(data = mubsey, aes(x = Years, y = median), color = "#E69F00", size = 0.8) + #, linetype = "dashed") +
  geom_ribbon(data = fpey, aes(x = Years, ymin = lower, ymax = upper),
              fill = "#0072B2", alpha = 0.2, color = NA) +
  geom_ribbon(data = mubsey, aes(x = Years, ymin = lower, ymax = upper),
              fill = "#E69F00", alpha = 0.2, color = NA) +
  geom_point(data = esubs, aes(x = Years, y = Cost_km, color = Protection_level),
             show.legend = FALSE) +
  scale_color_manual(
    values = c("Fully protected" = "#0072B2", "Partially protected" = "#E69F00"),
    labels = c("Fully protected" = "Fully protected areas",
               "Partially protected" = "Multi-use areas")
  ) +
  scale_y_continuous(
    trans = scales::pseudo_log_trans(base = 10),
    breaks = c(10, 1000, 100000, 10000000),
    labels = scales::label_log(),
    limits = c(0, 1e7)) +
  theme_bw() +
  theme(text = element_text(family = "serif", size=10),
         axis.title = element_blank(),
         # These lines remove the grid
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()) 

png("../Results/Figure.3.png", width = 2000, height = 2000, res = 300)  
#tot_years <- 
  neyear_pl +
  inset_element(
    leyear_pl,
     left = 0.02, 
    bottom = 0.6,
    right = 0.8,
    top = 0.98)
dev.off()

#final_plot + tot_years + plot_annotation(
   # theme = theme(
    #  plot.caption = element_text(hjust = 0.41, size = 10, family = "serif")),
    # caption = "Establishment phase (years)")
```

# plotting GDP per capita vs establishment costs

```{r}
# setting the model formula
formGDP = bf(Cost_km ~ GDP_pc, family = lognormal)
#model_gdp = lm(lCost_km ~ GDP_pc, family=gaussian, data = )
# running the model with priors only
GDP.brm1 = brm(formGDP, 
               data=esubs,
               sample_prior='yes', 
               iter= 5000, 
               warmup = 1000, 
               chains=3, 
               cores = 3, 
               thin=5, 
               refresh=0, 
               seed=123, 
               control = list(adapt_delta=0.99, max_treedepth=29),
               backend = "cmdstanr")

# Assess priors and posteriors
GDP.brm1 |> SUYR_prior_and_posterior()
# summarising results
#thorough results
GDP.brm1 |> 
  as_draws_df() |>  
  dplyr::select(matches("^b_.*")) |> 
  summarise_draws(
    median=median, 
                  hdi = ~HDInterval::hdi(.x),
                  rhat, 
                  ess_bulk,
                  Pl = ~mean(.x<0), 
                  Pg = ~mean(.x>0),
                  se = ~sd(.x))
```

## Plotting establisxhment costs x GDP per capita

```{r}
esubs <- esubs |> 
  filter(!is.na(GDP_pc))
newGDPseq <- seq(min(esubs$GDP_pc),
                 max(esubs$GDP_pc),
                 length.out = 100)
# getting the predicted draws
pred_draws_GDP_e <- emmeans(
  GDP.brm1,
  ~ GDP_pc,
  at = list(GDP_pc = newGDPseq
    #GDP_pc = seq(min(esubs$GDP_pc), max(esubs$GDP_pc), length.out = 100)
  )) |>
  gather_emmeans_draws()

# Now safely summarise per lSize using purrr
pred_GDP_e <- pred_draws_GDP_e |>
  group_by(GDP_pc) |>
  summarise(
    estimate = median(.value),
    lower = quantile(.value, 0.025),
    upper = quantile(.value, 0.975),
    .groups = "drop"
  ) |>
  mutate(
    response = exp(estimate),
    lower = exp(lower),
    upper = exp(upper))

# creating the base plot
GDP_base <- 
  ggplot(pred_GDP_e, aes(x = GDP_pc, y = response)) +
    geom_line(size = 0.8, color = "#8C1D40") +
    geom_ribbon(aes(ymin = lower, ymax = upper), fill = "#800020", alpha = 0.2, color = NA) +
    scale_y_continuous(
      labels = scales::label_number()) +
    scale_x_continuous(
      labels = scales::label_number(scale = 1e-3)) +
    theme_bw() +
    theme(text = element_text(family = "serif"),
          panel.border = element_rect(color = "black", fill = NA, linewidth = 0.2)
          #panel.grid.minor = element_blank(), 
          #panel.grid.major=element_blank()) +
          ) +
    labs(
      x = "GDP per capita (thousand US$)",
      y = "Estimated establishment costs (US$/km²)", 
      title = " ") + 
   coord_cartesian(
     xlim = c(0, 90000),
     ylim = c(0, 200000), 
     clip = "on") +
  annotate("text", x = -Inf, y = Inf, label = "A", hjust = 1.7, vjust = 0, size = 5, fontface = "bold", family = 'serif')
GDP_base

# creating the inset plot with log10 scale for the y axis
GDP_inset <-
 ggplot(pred_GDP_e, aes(x = GDP_pc, y = response)) +
  geom_line(size = 0.8, color = "#8C1D40") +  # thinner line
  geom_ribbon(aes(ymin = lower, ymax = upper), fill = "#800020", alpha = 0.2, color = NA) +
  geom_point(data = esubs, aes(x = GDP_pc, y = Cost_km), color = "#8C1D40") +
  theme_bw() +
  theme(text = element_text(family = "serif"), 
        axis.title = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_y_continuous(
    trans = scales::pseudo_log_trans(base = 10),
    breaks = c(10, 1000, 100000, 10000000),
    labels = scales::label_log(),
    limits = c(0, 1e7)) +
  scale_x_continuous(
    labels = scales::label_number(scale = 1e-3),
    limits = c(0, 90000))
GDP_inset
# combining base and inset plot for establishment
est_GDP <- 
  GDP_base + inset_element(
    GDP_inset,
    left = 0.3, # 30% distance from the left  
    bottom = 0.45, # 45% distance from the bottom
    right = 0.95, 
    top = 0.98)

# combining establishment and maintenance gdp per capita plots 
total_GDP <- 
  est_GDP + GDP 
png("../Results/Figure GDP.png", width = 2500, height = 1600, res = 300)
total_GDP
dev.off()
```

# Coefficient plot

## Establishment coefficients

```{r}
# saving posterior draws
posterior_draws_e <- esubs.brm1 |> 
  as_draws_df() |>  
  dplyr::select(matches("^b_.*")) |> 
  summarise_draws(
    median = median, 
    hdi = ~HDInterval::hdi(.x),
    rhat, 
    ess_bulk,
    Pl = ~mean(.x<0), 
    Pg = ~mean(.x>0), 
    se = ~sd(.x))
# filtering out the interaction because first deletion
posterior_draw_interaction <- posterior_draws_e |> 
  filter(rownames(posterior_draws_e) == "5")
# 1st deletion of the interaction term 
posterior_draws_1_delition_int <- esubs.brm1 |>
  as_draws_df() |>  
  dplyr::select(matches("^b_.*")) |> 
  summarise_draws(
    median = median, 
                  hdi = ~HDInterval::hdi(.x),
                  rhat, 
                  ess_bulk,
                  Pl = ~mean(.x<0), 
                  Pg = ~mean(.x>0),
                  se = ~sd(.x))
# making coefficient plot for establishment regression
est_coef <- ggplot() + 
  geom_point(data = posterior_draws_1_delition_int, 
             aes(x = median, y = seq_along(median), color = "Final model"), 
             size = 3) + 
  geom_errorbar(data = posterior_draws_1_delition_int, 
                aes(xmin = lower, xmax = upper, y = seq_along(median), color = "Final model"), 
                width = 0.2) + 
  scale_y_continuous(
    breaks = 1:5,
    labels = c("Intercept", 
               "ln(Size)", 
               "Duration",
               "Degree of protection¹\nMulti-use areas", 
               "Interaction¹\nln(Size):Multi-use areas")) +
  # adding point for the interaction term 
  geom_point(data = posterior_draw_interaction, 
             aes(x = median, y = 5, color = "1st deletion"), size = 3) +
  geom_errorbar(data = posterior_draw_interaction, 
                aes(xmin = lower, xmax = upper, y = 5, color = "1st deletion"), width = 0.2) +
  geom_vline(xintercept = 0, color = "black", linewidth = 0.2) +
  geom_text(data = data.frame(
    x = posterior_draws_1_delition_int$median[c(2,3,4)] + 1.2,
    y = c(2,3,4),
    label = c("**","*","*")),
    aes(x = x, y = y, label = label), size = 5) +
  theme_bw() + 
  theme(text = element_text(family = 'serif'), 
        axis.title = element_text(family = 'serif', face = 'plain'), 
        title = element_text(face = "bold"),
        legend.position = "none") + 
  labs(
    y = "Predictor variables",
    x = "Estimates (± Credible interval)", 
    title = "A - Total establishment costs \n      (US$/km²)") + 
  coord_cartesian(xlim = c(-3, 12.5)) +
  # creating a dummy layer for the legend
  geom_point(data = data.frame(
    model = c("1st deletion", "Final model"),
    x = c(NA, NA),
    y = c(NA, NA)),
  aes(x = x, y = y, color = model), size = 3) +
scale_color_manual(name = NULL,
  values = c(
    "1st deletion" = "#8C1D40",
    "Final model" = "royalblue4"))
est_coef
# saving posterior drws for maintenance
posterior_draws_m <- msubs.brm1 |>
  as_draws_df() |>  
  dplyr::select(matches("^b_.*")) |> 
  summarise_draws(
    median = median, 
                  hdi = ~HDInterval::hdi(.x),
                  rhat, 
                  ess_bulk,
                  Pl = ~mean(.x<0), 
                  Pg = ~mean(.x>0),
                  se = ~sd(.x))
# filtering out GDP because first deletion
posterior_draw_gdp <- posterior_draws_m |> 
  filter(rownames(posterior_draws_m) == "3")
# posterior draws after first delition
posterior_draws_1_deletion <- msubs.brm1 |>
  as_draws_df() |>  
  dplyr::select(matches("^b_.*")) |> 
  summarise_draws(
    median = median, 
                  hdi = ~HDInterval::hdi(.x),
                  rhat, 
                  ess_bulk,
                  Pl = ~mean(.x<0), 
                  Pg = ~mean(.x>0),
                  se = ~sd(.x))

# plotting coefficient plot for maintenance regression
maint_coef <- ggplot() + 
  geom_point(data = posterior_draws_1_deletion, 
             aes(x = median, y = seq_along(median), color = "Final model"), 
             size = 3) + 
  geom_errorbar(data = posterior_draws_1_deletion, 
                aes(xmin = lower, xmax = upper, y = seq_along(median), color = "Final model"), 
                width = 0.2) + 
  scale_y_continuous(
    breaks = 1:5,
    labels = c("Intercept", 
               "ln(Size)", 
               "Degree of protection¹\nMulti-use areas", 
               "Interaction¹\nln(Size):Multi-use areas", 
               "GDP per capita")) +
  # adding point for the interaction term 
  geom_point(data = posterior_draw_gdp, 
             aes(x = median, y = 5, color = "1st deletion"), size = 3) +
  geom_errorbar(data = posterior_draw_gdp, # this does not work - but the error bars are so small that you cant see them on the plot
               aes(xmin = lower, xmax = upper, y = 5, color = "1st deletion"), width = 0.2) +
  geom_vline(xintercept = 0, color = "black", linewidth = 0.2) +
  geom_text(data = data.frame(
    x = posterior_draws_1_deletion$median[c(2,4)] + 1.3,
    y = c(2,4),
    label = c("**","*")),
    aes(x = x, y = y, label = label), size = 5) +
  theme_bw() + 
  theme(text = element_text(family = 'serif'), 
        axis.title.y = element_blank(), 
        axis.title.x = element_text(face = 'plain'),
        title = element_text(face = 'bold'), 
        legend.title = element_text(face = 'plain')) + 
  labs(
    x = "Estimates (± Credible interval)",
    title = "B - Annual maintenance costs \n      (US$/km² per annum)") + 
  coord_cartesian(xlim = c(-3, 12.5)) +
  # creating a dummy layer for the legend
  geom_point(data = data.frame(
    model = c("1st deletion", "Final model"),
    x = c(NA, NA),
    y = c(NA, NA)),
  aes(x = x, y = y, color = model), size = 3) +
scale_color_manual(name = "Backward deletion steps",
  values = c(
    "1st deletion" = "#8C1D40",
    "Final model" = "royalblue4"))
maint_coef

# Combining plots
coefficient_plots <- est_coef + maint_coef
# Export the plot
png("../Results/coefficients plot.png", width = 2800, height = 1400, res = 300)
coefficient_plots
dev.off()
```

# Extra stats - editor
```{r}
mE_offset <- bf(Cost_km ~ offset(log(Size)) + Years, family = lognormal)
offset_brms <- brm(mE_offset, 
               data = esubs, 
               sample_prior ='yes', 
               iter = 5000, 
               warmup = 1000, 
               chains = 3, 
               cores = 3, 
               thin = 5, 
               refresh = 0, 
               seed = 123, 
               control = list(adapt_delta = 0.99, max_treedepth = 29),
               backend = "cmdstanr")

mE_cov <- bf(Cost_km ~ log(Size) + Years, family = lognormal)
cov_brms <- brm(mE_cov, 
               data = esubs, 
               sample_prior ='yes', 
               iter = 5000, 
               warmup = 1000, 
               chains = 3, 
               cores = 3, 
               thin = 5, 
               refresh = 0, 
               seed = 123, 
               control = list(adapt_delta = 0.99, max_treedepth = 29),
               backend = "cmdstanr")

loo_compare(loo(offset_brms), loo(cov_brms))
```