---
title: "Ch3-MPAcosts"
---

# Loading packages needed fro the project

```{r}
library(readr)
library(ggplot2)
library(rnaturalearth) # to make a world map
library(rnaturalearthdata) # data for world map with polygons of the coastline only
library(dplyr)
library(sf)
library(ggspatial) # to add spatial elements to a ggplot map
library(car)
```

# Making a map of the MPAs I found data for

## Loading the map data

```{r}
#upload the right data
fig1 <- read_csv("../Data/fig1.csv")
```

## Making global map with my data

```{r}
# Get world map data
world <- ne_countries(scale = "medium", returnclass = "sf")

png("Map1.png", width = 2500, height = 2000, res = 150)
# Create the world map
# Load the coastline data from rnaturalearth
coastline_data <- ne_coastline(scale = "medium", returnclass = "sf")

# Create the plot
ggplot() +  
  # Plot countries in a very light grey
  geom_sf(data = world, fill = "grey95", color = NA) +  
  # Overlay the coastline in black
  geom_sf(data = coastline_data, color = "black", fill = NA) +  
  # Plot your data points
  geom_point(data = fig1, aes(x = Longitude, y = Latitude), color = "#008080", size = 4) +  
  # Set coordinate system
  coord_sf() +
  # Adjust theme
  theme_minimal() +  
  theme(
    axis.text = element_text(size = 24),
    axis.title = element_blank(),  # Removes axis titles
    axis.line.x = element_line(color = "black", size = 0.5),
    axis.line.y = element_line(color = "black", size = 0.5),
    axis.ticks = element_line(color = "black", size = 0.5),
    panel.grid = element_blank()
  )
dev.off()

```






# Statistics

## Loading the data
```{r}
#loading the data
data <- read_csv("../Data/ch3data.csv")
View(data)
#setting up the data
data = data |> mutate(Protection_level=factor(Protection_level))
```


## Data exploration
```{r}
#looking at distribution for costs/km2 divided by gdp class
boxplot(Cost_km~GDP_class, data=data)
#looking at the distribution for cost/km2
hist(data$Cost_km, breaks=60)
#distribution of total costs 
hist(data$'2024_AUD', breaks=60)
#looking at the distribution of costs/km2 divided by cost category
boxplot(Cost_km~Protection_level, data=data)
```

```{r}
#model
# Linear regression model with the specified predictors
model <- lm(Cost_km ~ Protection_level + GDP_pc, data = data)

# View the summary of the model
summary(model)
vif(model)

#plot
plot(model)

# Plot the residuals to check for normality (Gaussian distribution)
#par(mfrow = c(1, 2))  # Set up a 2-panel plot
#plot(model$fitted.values, model$residuals, main = "Residuals vs Fitted", xlab = "Fitted Values", ylab = "Residuals")
#hist(model$residuals, breaks = 30, main = "Histogram of Residuals", xlab = "Residuals", col = "lightblue", border = "black")

```
## Making three different models
```{r}
#filtering data based on: establishment, maintenance and compliance
establishment = filter(data, Cost_class == "Establishment")
# Linear regression model with the specified predictors
model1 <- lm(Cost_km ~ Protection_level + GDP_pc, data = establishment)
# View the summary of the model
summary(model1)
plot(model1)
View(establishment)

#filtering data based on: establishment, maintenance and compliance
maintenance = filter(data, Cost_class == "Maintenance") # see notes this is not displaying all the maintenance data I have 
#maintenance1 = filter(data, Cost_class %in% c("Administration", "Enforcement", "Management", "Maintenance"))
# Linear regression model with the specified predictors
model2 <- lm(Cost_km ~ Protection_level + GDP_pc, data = maintenance1) # not enough data for this
# View the summary of the model
summary(model2)
plot(model2)
View(maintenance)
```
## Combining and dummy coding levels

```{r}
#using maintenance coded with subs 
msubs <- read_csv("../Data/msubs.csv")
#prepering data
msubs = msubs |> mutate(Protection_level=factor(Protection_level))
View(msubs)
#exploratory model
m1 <- lm(Cost_km ~ Protection_level + GDP_pc + Management +Administration+Enforcement, data=msubs)
summary(m1)
plot(m1)
vif(m1)
```











