---
title: "Figures"
format: html
---

# Library

```{r}
library(ggplot2)
library(dplyr)
library(patchwork)
```

# Figure 3: Costs of establishment phase for each degree of protection

```{r}
# making prediction 
esubs <- esubs |> 
  filter(!is.na(Years)) 

pred_draws1 <- emmeans(
  esubs.brm2,
  ~ Years | Protection_level,
  at = list(
    Years = seq(min(esubs$Years), max(esubs$Years), length.out = 100),
    lSize = mean(esubs$lSize, na.rm = TRUE),
    Protection_level = unique(esubs$Protection_level))) |>
  gather_emmeans_draws() |>
  mutate(.value = exp(.value))

pred_year1 <- pred_draws1 |>
  group_split(Years) |>
  map_dfr(function(df) {
    hdi_vals <- hdi(df$.value)
    tibble(
      Years    = unique(df$Years),
      Protection_level = unique(df$Protection_level),
      median    = median(df$.value),
      lower.HPD = hdi_vals[1],
      upper.HPD = hdi_vals[2]
    )
  })
#View(pred_year1)

# plotting 
fpey <- subset(pred_year1, Protection_level == "Fully protected")
mubsey <- subset(pred_year1, Protection_level == "Partially protected")
# Create the plot - base plot 
neyear_pl <- 
  ggplot() +
  # Fully protected areas
  geom_line(data = fpey, aes(x = Years, y = median, color = "Fully protected areas"), size = 0.8) +
  geom_ribbon(data = fpey, aes(x = Years, ymin = lower.HPD, ymax = upper.HPD, fill = "Fully protected areas"), alpha = 0.2) +
  # Partially protected areas
  geom_line(data = mubsey, aes(x = Years, y = median, color = "Multi-use areas"), size = 0.8) +
  geom_ribbon(data = mubsey, aes(x = Years, ymin = lower.HPD, ymax = upper.HPD, fill = "Multi-use areas"), alpha = 0.2) +
  # Customize scales
  scale_color_manual(values = c("Fully protected areas" = "#0072B2", "Multi-use areas" = "#E69F00")) +
  scale_fill_manual(values = c("Fully protected areas" = "#0072B2", "Multi-use areas" = "#E69F00")) +
  # Scientific notation for y-axis
  scale_y_continuous(
    labels = scales::label_number(scale = 1e-6), 
                     limits=c(0, 2e06)) +
  # Apply theme
  theme_bw() +
  theme(text = element_text(family = "serif"), 
        #panel.grid.major = element_blank(),
        #panel.grid.minor = element_blank(), 
        legend.position = "right", 
        #axis.title = element_blank(), # remove axis titles
        panel.border = element_rect(colour = "black", fill = NA, size = 0.25) # change thickness of the outside boarder
        ) +
  # Labels
  labs(
    x = "Establishment phase (years)",
    y = "Estimated establishment costs (million US$/km²)",
    color = "Degree of Protection",
    fill = "Degree of Protection") +
  coord_cartesian(clip="off") 

# Creating inset plot with log10 scale for teh y axis
leyear_pl = 
  ggplot() +
  geom_line(data = fpey, aes(x = Years, y = median), color = "#0072B2", size = 0.8) +
  geom_line(data = mubsey, aes(x = Years, y = median), color = "#E69F00", size = 0.8) +
  geom_ribbon(data = fpey, aes(x = Years, ymin = lower.HPD, ymax = upper.HPD),
              fill = "#0072B2", alpha = 0.2, color = NA) +
  geom_ribbon(data = mubsey, aes(x = Years, ymin = lower.HPD, ymax = upper.HPD),
              fill = "#E69F00", alpha = 0.2, color = NA) +
  geom_point(data = esubs, aes(x = Years, y = Cost_km, color = Protection_level),
             show.legend = FALSE) +
  scale_color_manual(
    values = c("Fully protected" = "#0072B2", "Partially protected" = "#E69F00"),
    labels = c("Fully protected" = "Fully protected areas",
               "Partially protected" = "Multi-use areas")
  ) +
  scale_y_log10(
    labels = scales::label_log(), 
                limits = c(1e0, 1.0e+07)) +
  theme_bw() +
  theme(text = element_text(family = "serif", size=10),
         axis.title = element_blank(),
         # These lines remove the grid
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()) 

png("../Results/Figure.3.png", width = 1900, height = 2000, res = 300)  
#tot_years <- 
  neyear_pl +
  inset_element(
    leyear_pl,
     left = 0.02, 
    bottom = 0.6,
    right = 0.8,
    top = 0.98)
dev.off()

#final_plot + tot_years + plot_annotation(
   # theme = theme(
    #  plot.caption = element_text(hjust = 0.41, size = 10, family = "serif")),
    # caption = "Establishment phase (years)")

```
# plotting GDP per capita vs establishment costs 
```{r}
# setting the model formula
formGDP = bf(lCost_km ~ scale(GDP_pc), family=gaussian)
# setting my priors
priors = prior(normal(11, 1.8), class='Intercept') +
  prior(normal(0,1.8), class='b')
# running the model with priors only
GDP.brm1 = brm(formGDP, 
               data=esubs, 
               prior=priors,
               sample_prior='only', 
               iter= 5000, 
               warmup = 1000, 
               chains=3, 
               cores = 3, 
               thin=5, 
               refresh=0, 
               seed=123, 
               control = list(adapt_delta=0.99, max_treedepth=29),
               backend = "cmdstanr")
# running the model with both priors and data
GDP.brm2 = GDP.brm1 |> 
  update(sample_prior = 'yes', refresh=100)
# Assess priors and posteriors
GDP.brm2 |> SUYR_prior_and_posterior()
# summarising results
#thorough results
GDP.brm2 |> 
  as_draws_df() |>  
  dplyr::select(matches("^b_.*")) |> 
  summarise_draws(
    median=~exp(median(.x)), 
    hdi = ~HDInterval::hdi(exp(.x)),
    rhat, 
    ess_bulk,
    Pl=~mean(.x<1), 
    Pg=~mean(.x>1))
```
## Plottign establisxhment costs x GDP per capita
```{r}
# creating prediction dataframe
pred_draws_GDP_e <- emmeans(
  GDP.brm2,
  ~ GDP_pc,
  at = list(
    GDP_pc = seq(min(esubs$GDP_pc), max(esubs$GDP_pc), length.out = 100)
  )) |>
  gather_emmeans_draws() |>
  mutate(.value = exp(.value))  # back-transform from log the response variable --> Cost_km

# Now safely summarise per lSize using purrr
pred_GDP_e <- pred_draws_GDP_e |>
  group_split(GDP_pc) |>
  map_dfr(function(df) {
    hdi_vals <- hdi(df$.value)
    tibble(
      GDP_pc    = unique(df$GDP_pc),
      response  = median(df$.value),
      lower.HPD = hdi_vals[1],
      upper.HPD = hdi_vals[2]
    )
  })

# creating the base plot
GDP_base <- 
  ggplot(pred_GDP_e, aes(x = GDP_pc, y = response)) +
    geom_line(size = 0.8) +
    geom_ribbon(aes(ymin = lower.HPD, ymax = upper.HPD), alpha = 0.2, color = NA) +
    scale_y_continuous(
      labels = scales::label_number(scale = 1e-3)) +
    scale_x_continuous(
      labels = scales::label_number(scale = 1e-3)) +
    theme_bw() +
    theme(text = element_text(family = "serif") #,   
          #panel.grid.minor = element_blank(), 
          #panel.grid.major=element_blank()) +
          ) +
    labs(
      x = "GDP per capita (thousand US$)",
      y = "Estimated maintenance costs (thousand US$/km² p.a.)", 
      title = " ") + 
   coord_cartesian(clip="off") +
  annotate("text", x=-Inf, y=Inf, label="A", hjust=1.7, vjust=0, size=5, fontface="bold", family='serif')
GDP_base

# creating the inset plot with log10 scale for the y axis
GDP_inset <-
 ggplot(pred_GDP_e, aes(x = GDP_pc, y = response)) +
  geom_line(size = 0.8) +  # thinner line
  geom_ribbon(aes(ymin = lower.HPD, ymax = upper.HPD), alpha = 0.2, color = NA) +
  geom_point(data=msubs, aes(x=GDP_pc, y=Cost_km)) +
  theme_bw() +
  theme(text = element_text(family = "serif"), 
        axis.title = element_blank(), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  scale_y_log10(
    labels = scales::label_log()
  ) +
  scale_x_continuous(
    labels = scales::label_number(scale = 1e-3))
GDP_inset
# combining base and inset plot for establishment
est_GDP <- 
  GDP_base + inset_element(
    GDP_inset,
    left = 0.3, # 25% distance from the left  
    bottom = 0.45, # 45% distance from the bottom
    right = 0.95, 
    top = 0.98)

# combining establishment and maintenance gdp per capita plots 
total_GDP <- 
  est_GDP + GDP 
png("../Results/Fifgure GDP.png", width = 2500, height = 1600, res = 300)
total_GDP
dev.off()
  
```










